---
title: "Brazilian Court Decisions"
always_allow_html: yes
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    orientation: rows 
    css: styles.css
    favicon: favicon.png 
---

```{r Setup, include=FALSE}

knitr::opts_chunk$set(
  echo = F,
  warning = F,
  message = F,
  error = TRUE
)

```

```{r Preprocessing, echo=FALSE, results='hide', message=FALSE, warning=FALSE, fig.show='hide'}

# general functions and R package loads
install.and.load <- function(vPacotes)
{
  for (pac in vPacotes) {
    if (!require(pac, character.only = T)) {
      install.packages(pac)
      library(pac, character.only = T)
    }
  }
}

install.and.load(
  c(
    'here',
    'ggplot2',
    'scales',
    'grid',
    'gridExtra',
    'dplyr',
    'tidyr',
    'stringr',
    'plotly',
    'ggthemes',
    'flexdashboard'
  )
)

if (!require("processx"))
  install.packages("processx")

cairo_pdf <- 'pdf'

mycat <- function(text) {
  cat(gsub(
    pattern = "\n",
    replacement = "  \n",
    x = text
  ))
}

# returns string w/o leading or trailing whitespace
trim <- function (x)
  gsub("^\\s+|\\s+$", "", x)
trim_all <- function(x)
  gsub(" ", "", x, fixed = TRUE)
trim_rs <- function(x)
  gsub("r$", "", x)


options(digits = 10, scipen = 99)

# color palletes
COLOR_GRID <- "#f0f0f0"
OKABE_ITO <- c(
  "sky_blue"       = rgb(86, 180, 233, maxColorValue = 255),
  "blue"           = rgb(0, 114, 178, maxColorValue = 255),
  "reddish_purple" = rgb(204, 121, 167, maxColorValue = 255),
  "vermillion"     = rgb(213,  94,   0, maxColorValue = 255),
  "bluish_green"   = rgb(0, 158, 115, maxColorValue = 255),
  "yellow"         = rgb(240, 228,  66, maxColorValue = 255),
  "orange"         = rgb(230, 159,   0, maxColorValue = 255),
  "black"          = rgb(0,   0,   0, maxColorValue = 255)
)


OkabeIto <- function(x) {
  return (as.character(OKABE_ITO[x]))
}

GRAYS <- c('#cccccc', '#999999', '#666666', '#333333')

BLUES <- c('#AADDFF', '#77AACC', '#447799', '#114466')

LBLUE <- '#B3CDE3'

GREENS <- c("#00d19c", "#009e74", "#004f3b")

doc.colors <- c(BLUES[1], BLUES[2], BLUES[4])
names(doc.colors) <- c("R", "1a", "2a")

proc.colors <- GRAYS
names(proc.colors) <-
  c("PROCEDIMENTO", "REEMBOLSO", "TRATAMENTO", "MEDICAMENTO_EME")

flag.colors <- c("#004f3b", "#cccccc")
names(flag.colors) <- c("Provided", "Not provided")

levels.colors <- c(GREENS[1], GREENS[2], GREENS[3])
names(levels.colors) <- c("lower", "equal", "higher")


# plots definitions
#margin
m <- list(
  l = 50,
  r = 50,
  b = 100,
  t = 100,
  pad = 4
)

#font
f <- list(size = 16)

#title
tit <- list(size = 12)

af <- list(size = 12)

# document array - levels definition
xform <- list(categoryorder = "array",
              categoryarray = c("R",
                                "1a",
                                "2a"))

```

```{r Database, echo=FALSE, results='hide', message=FALSE, warning=FALSE, fig.show='hide'}

# database loads
dfRepTrialAppell_dm <- readRDS(file = "in/dfRepTrialAppell_dm.Rds")
dfAppellbyCID_dm <- readRDS(file = "in/dfAppellbyCID_dm.Rds")

dfRepTrialAppell_reemb <-
  readRDS(file = "in/dfRepTrialAppell_reemb.Rds")

dfRepTrial_req <- readRDS(file = "in/dfRepTrial_req.Rds")
dfAppellbyCID_reemb <- readRDS(file = "in/dfAppellbyCID_reemb.Rds")


```

All law suits {data-navmenu="Moral damage" data-icon="fa-file-alt"} 
=========================================================================================================

### 
> All law suits


Row
---------------------------------------------------------------------------------------------------------
```{r}

# database for plotting All law suits
dfPlot <-
  dfRepTrialAppell_dm %>% filter(!(document == "R" & value == "0"))
```


### Report
```{r}

# display number of reports documents
R_N <- dfPlot %>% filter(document == "R") %>% summarise(n())
valueBox(value = R_N,
         icon = "fa-balance-scale",
         color = doc.colors[1])
```

### Lower Court
```{r}

# display number of lower court documents
R_L <- dfPlot %>% filter(document == "1a") %>% summarise(n())
valueBox(value = R_L,
         icon = "fa-balance-scale",
         color = doc.colors[2])

```

### Appellate Court
```{r}

# display number of appellate court documents
R_A <- dfPlot %>% filter(document == "2a") %>% summarise(n())
valueBox(value = R_A,
         icon = "fa-balance-scale",
         color = doc.colors[3])
```

Row
-------------------------------------

### 

```{r, fig.align="center"}

# get group of unique CIDS (CID_GRUPO, CID_NOME)
group_cids <- unique(dfPlot[, c('CID_GRUPO', 'CID_NOME')])

# unify "Pregancy", "Childbirth and  post-childbirth"
cid_en_names <-
  c(
    "Undefined",
    "Respiratory",
    "Digestive",
    "Eye",
    "Congenital",
    "Neoplasm",
    "Not informed",
    "Infectious",
    "Endocrine",
    "Mental",
    "Circulatory",
    "Musculoskeletal",
    "Genitourinary",
    "Nervous",
    "Poisoning",
    "Skin",
    "Blood",
    "Perinatal",
    "Childbirth and  post-childbirth",
    "Exams",
    "Health services",
    "Ear",
    "Death"
  )

# translate CID_NOME: PT > EN
group_cids$CID_NOME_EN <- cid_en_names

# count documents for display on the axis
R_N <- dfPlot %>% filter(document == "R") %>% summarise(n())
R_L <- dfPlot %>% filter(document == "1a") %>% summarise(n())
R_A <- dfPlot %>% filter(document == "2a") %>% summarise(n())


# generate plot:: Granted values for moral damages: \nall law suits and appeals analyzed
viz <-
  plot_ly(
    dfPlot,
    y = ~ value,
    color = ~ document,
    type = "box",
    colors = doc.colors,
    showlegend = FALSE,
    width = 500,
    height = 500
  ) %>%
  layout(
    title = "Granted values for moral damages: \nall law suits and appeals analyzed",
    yaxis = list(font = f, title = "Amount (R$)"),
    xaxis = list(
      font = f,
      title = "",
      ticktext = list(
        paste0("Report \n(N = ", R_N[[1]], ")"),
        paste0("Lower Court \n(N = ", R_L[[1]], ")"),
        paste0("Appellate Court \n(N = ", R_A[[1]], ")")
      ),
      tickvals = list("R", "1a", "2a"),
      tickmode = "array",
      categoryarray = c("R", "1a", "2a"),
      categoryorder = "array"
    ),
    
    margin = m
  )

viz

```



Row
-------------------------------------   

### 

```{r}

# filter Undefined chapter
dfPlot_filter <-
  dfPlot %>% filter(CID_GRUPO == group_cids[1, "CID_GRUPO"])

# count documents for display on the axis
R_N <- dfPlot_filter %>% filter(document == "R") %>% summarise(n())
R_L <- dfPlot_filter %>% filter(document == "1a") %>% summarise(n())
R_A <- dfPlot_filter %>% filter(document == "2a") %>% summarise(n())

# generate plot:: Granted values for moral damages related to the same law suits of the Undefined chapter: all law suits and appeals analyzed
viz <-
  plot_ly(
    dfPlot_filter,
    y = ~ value,
    color = ~ document,
    type = "box",
    colors = doc.colors,
    showlegend = FALSE,
    width = 500,
    height = 500
  ) %>%
  layout(
    title = paste0(
      "Granted values for moral damages related to \nthe same law suits of the ",
      group_cids[1, "CID_NOME_EN"],
      " chapter: \nall law suits and appeals analyzed"
    ),
    yaxis = list(font = f, title = "Amount (R$)"),
    xaxis = list(
      font = f,
      title = "",
      ticktext = list(
        paste0("Report \n(N = ", R_N[[1]], ")"),
        paste0("Lower Court \n(N = ", R_L[[1]], ")"),
        paste0("Appellate Court \n(N = ", R_A[[1]], ")")
      ),
      tickvals = list("R", "1a", "2a"),
      tickmode = "array",
      categoryarray = c("R", "1a", "2a"),
      categoryorder = "array"
    ),
    
    margin = m
  )

viz


```

### 


```{r}
# filter Respiratory chapter
dfPlot_filter <-
  dfPlot %>% filter(CID_GRUPO == as.character(group_cids[2, "CID_GRUPO"]))

# count documents for display on the axis
R_N <- dfPlot_filter %>% filter(document == "R") %>% summarise(n())
R_L <- dfPlot_filter %>% filter(document == "1a") %>% summarise(n())
R_A <- dfPlot_filter %>% filter(document == "2a") %>% summarise(n())

# generate plot:: Granted values for moral damages related to the same law suits of the Respiratory chapter: all law suits and appeals analyzed
viz <-
  plot_ly(
    dfPlot_filter,
    y = ~ value,
    color = ~ document,
    type = "box",
    colors = doc.colors,
    showlegend = FALSE,
    width = 500,
    height = 500
  ) %>%
  layout(
    title = paste0(
      "Granted values for moral damages related to \nthe same law suits of the ",
      group_cids[2, "CID_NOME_EN"],
      " chapter: \nall law suits and appeals analyzed"
    ),
    yaxis = list(font = f, title = "Amount (R$)"),
    xaxis = list(
      font = f,
      title = "",
      ticktext = list(
        paste0("Report \n(N = ", R_N[[1]], ")"),
        paste0("Lower Court \n(N = ", R_L[[1]], ")"),
        paste0("Appellate Court \n(N = ", R_A[[1]], ")")
      ),
      tickvals = list("R", "1a", "2a"),
      tickmode = "array",
      categoryarray = c("R", "1a", "2a"),
      categoryorder = "array"
    ),
    
    margin = m
  )

viz

```


### 


```{r}

# filter Digestive chapter
dfPlot_filter <-
  dfPlot %>% filter(CID_GRUPO == as.character(group_cids[3, "CID_GRUPO"]))

# count documents for display on the axis
R_N <- dfPlot_filter %>% filter(document == "R") %>% summarise(n())
R_L <- dfPlot_filter %>% filter(document == "1a") %>% summarise(n())
R_A <- dfPlot_filter %>% filter(document == "2a") %>% summarise(n())

# generate plot:: Granted values for moral damages related to the same law suits of the Digestive chapter: all law suits and appeals analyzed
viz <-
  plot_ly(
    dfPlot_filter,
    y = ~ value,
    color = ~ document,
    type = "box",
    colors = doc.colors,
    showlegend = FALSE,
    width = 500,
    height = 500
  ) %>%
  layout(
    title = paste0(
      "Granted values for moral damages related to \nthe same law suits of the ",
      group_cids[3, "CID_NOME_EN"],
      " chapter: \nall law suits and appeals analyzed"
    ),
    yaxis = list(font = f, title = "Amount (R$)"),
    xaxis = list(
      font = f,
      title = "",
      ticktext = list(
        paste0("Report \n(N = ", R_N[[1]], ")"),
        paste0("Lower Court \n(N = ", R_L[[1]], ")"),
        paste0("Appellate Court \n(N = ", R_A[[1]], ")")
      ),
      tickvals = list("R", "1a", "2a"),
      tickmode = "array",
      categoryarray = c("R", "1a", "2a"),
      categoryorder = "array"
    ),
    
    margin = m
  )

viz


```

Row
-------------------------------------

### 

```{r}
# filter Eye chapter
dfPlot_filter <-
  dfPlot %>% filter(CID_GRUPO == as.character(group_cids[4, "CID_GRUPO"]))

# count documents for display on the axis
R_N <- dfPlot_filter %>% filter(document == "R") %>% summarise(n())
R_L <- dfPlot_filter %>% filter(document == "1a") %>% summarise(n())
R_A <- dfPlot_filter %>% filter(document == "2a") %>% summarise(n())

# generate plot:: Granted values for moral damages related to the same law suits of the Eye chapter: all law suits and appeals analyzed
viz <-
  plot_ly(
    dfPlot_filter,
    y = ~ value,
    color = ~ document,
    type = "box",
    colors = doc.colors,
    showlegend = FALSE,
    width = 500,
    height = 500
  ) %>%
  layout(
    title = paste0(
      "Granted values for moral damages related to \nthe same law suits of the ",
      group_cids[4, "CID_NOME_EN"],
      " chapter: \nall law suits and appeals analyzed"
    ),
    yaxis = list(font = f, title = "Amount (R$)"),
    xaxis = list(
      font = f,
      title = "",
      ticktext = list(
        paste0("Report \n(N = ", R_N[[1]], ")"),
        paste0("Lower Court \n(N = ", R_L[[1]], ")"),
        paste0("Appellate Court \n(N = ", R_A[[1]], ")")
      ),
      tickvals = list("R", "1a", "2a"),
      tickmode = "array",
      categoryarray = c("R", "1a", "2a"),
      categoryorder = "array"
    ),
    
    margin = m
  )

viz


```

### 


```{r}

# filter Congenital chapter
dfPlot_filter <-
  dfPlot %>% filter(CID_GRUPO == as.character(group_cids[5, "CID_GRUPO"]))

# count documents for display on the axis
R_N <- dfPlot_filter %>% filter(document == "R") %>% summarise(n())
R_L <- dfPlot_filter %>% filter(document == "1a") %>% summarise(n())
R_A <- dfPlot_filter %>% filter(document == "2a") %>% summarise(n())

# generate plot:: Granted values for moral damages related to the same law suits of the Congenital chapter: all law suits and appeals analyzed
viz <-
  plot_ly(
    dfPlot_filter,
    y = ~ value,
    color = ~ document,
    type = "box",
    colors = doc.colors,
    showlegend = FALSE,
    width = 500,
    height = 500
  ) %>%
  layout(
    title = paste0(
      "Granted values for moral damages related to \nthe same law suits of the ",
      group_cids[5, "CID_NOME_EN"],
      " chapter: \nall law suits and appeals analyzed"
    ),
    yaxis = list(font = f, title = "Amount (R$)"),
    xaxis = list(
      font = f,
      title = "",
      ticktext = list(
        paste0("Report \n(N = ", R_N[[1]], ")"),
        paste0("Lower Court \n(N = ", R_L[[1]], ")"),
        paste0("Appellate Court \n(N = ", R_A[[1]], ")")
      ),
      tickvals = list("R", "1a", "2a"),
      tickmode = "array",
      categoryarray = c("R", "1a", "2a"),
      categoryorder = "array"
    ),
    
    margin = m
  )

viz


```

### 



```{r}

# filter Neoplasm chapter
dfPlot_filter <-
  dfPlot %>% filter(CID_GRUPO == as.character(group_cids[6, "CID_GRUPO"]))

# count documents for display on the axis
R_N <- dfPlot_filter %>% filter(document == "R") %>% summarise(n())
R_L <- dfPlot_filter %>% filter(document == "1a") %>% summarise(n())
R_A <- dfPlot_filter %>% filter(document == "2a") %>% summarise(n())

# generate plot:: Granted values for moral damages related to the same law suits of the Neoplasm chapter: all law suits and appeals analyzed
viz <-
  plot_ly(
    dfPlot_filter,
    y = ~ value,
    color = ~ document,
    type = "box",
    colors = doc.colors,
    showlegend = FALSE,
    width = 500,
    height = 500
  ) %>%
  layout(
    title = paste0(
      "Granted values for moral damages related to \nthe same law suits of the ",
      group_cids[6, "CID_NOME_EN"],
      " chapter: \nall law suits and appeals analyzed"
    ),
    yaxis = list(font = f, title = "Amount (R$)"),
    xaxis = list(
      font = f,
      title = "",
      ticktext = list(
        paste0("Report \n(N = ", R_N[[1]], ")"),
        paste0("Lower Court \n(N = ", R_L[[1]], ")"),
        paste0("Appellate Court \n(N = ", R_A[[1]], ")")
      ),
      tickvals = list("R", "1a", "2a"),
      tickmode = "array",
      categoryarray = c("R", "1a", "2a"),
      categoryorder = "array"
    ),
    
    margin = m
  )

viz


```

Row
-------------------------------------

### 

```{r}

# filter Not informed chapter
dfPlot_filter <-
  dfPlot %>% filter(CID_GRUPO == as.character(group_cids[7, "CID_GRUPO"]))

# count documents for display on the axis
R_N <- dfPlot_filter %>% filter(document == "R") %>% summarise(n())
R_L <- dfPlot_filter %>% filter(document == "1a") %>% summarise(n())
R_A <- dfPlot_filter %>% filter(document == "2a") %>% summarise(n())

# generate plot:: Granted values for moral damages related to the same law suits of the Not informed chapter: all law suits and appeals analyzed
viz <-
  plot_ly(
    dfPlot_filter,
    y = ~ value,
    color = ~ document,
    type = "box",
    colors = doc.colors,
    showlegend = FALSE,
    width = 500,
    height = 500
  ) %>%
  layout(
    title = paste0(
      "Granted values for moral damages related to \nthe same law suits of the ",
      group_cids[7, "CID_NOME_EN"],
      " chapter: \nall law suits and appeals analyzed"
    ),
    yaxis = list(font = f, title = "Amount (R$)"),
    xaxis = list(
      font = f,
      title = "",
      ticktext = list(
        paste0("Report \n(N = ", R_N[[1]], ")"),
        paste0("Lower Court \n(N = ", R_L[[1]], ")"),
        paste0("Appellate Court \n(N = ", R_A[[1]], ")")
      ),
      tickvals = list("R", "1a", "2a"),
      tickmode = "array",
      categoryarray = c("R", "1a", "2a"),
      categoryorder = "array"
    ),
    
    margin = m
  )

viz


```

### 


```{r}

# filter Infectious chapter
dfPlot_filter <-
  dfPlot %>% filter(CID_GRUPO == as.character(group_cids[8, "CID_GRUPO"]))

# count documents for display on the axis
R_N <- dfPlot_filter %>% filter(document == "R") %>% summarise(n())
R_L <- dfPlot_filter %>% filter(document == "1a") %>% summarise(n())
R_A <- dfPlot_filter %>% filter(document == "2a") %>% summarise(n())

# generate plot:: Granted values for moral damages related to the same law suits of the Infectious chapter: all law suits and appeals analyzed
viz <-
  plot_ly(
    dfPlot_filter,
    y = ~ value,
    color = ~ document,
    type = "box",
    colors = doc.colors,
    showlegend = FALSE,
    width = 500,
    height = 500
  ) %>%
  layout(
    title = paste0(
      "Granted values for moral damages related to \nthe same law suits of the ",
      group_cids[8, "CID_NOME_EN"],
      " chapter: \nall law suits and appeals analyzed"
    ),
    yaxis = list(font = f, title = "Amount (R$)"),
    xaxis = list(
      font = f,
      title = "",
      ticktext = list(
        paste0("Report \n(N = ", R_N[[1]], ")"),
        paste0("Lower Court \n(N = ", R_L[[1]], ")"),
        paste0("Appellate Court \n(N = ", R_A[[1]], ")")
      ),
      tickvals = list("R", "1a", "2a"),
      tickmode = "array",
      categoryarray = c("R", "1a", "2a"),
      categoryorder = "array"
    ),
    
    margin = m
  )

viz


```

### 



```{r}

# filter Endocrine chapter
dfPlot_filter <-
  dfPlot %>% filter(CID_GRUPO == as.character(group_cids[9, "CID_GRUPO"]))

# count documents for display on the axis
R_N <- dfPlot_filter %>% filter(document == "R") %>% summarise(n())
R_L <- dfPlot_filter %>% filter(document == "1a") %>% summarise(n())
R_A <- dfPlot_filter %>% filter(document == "2a") %>% summarise(n())

# generate plot:: Granted values for moral damages related to the same law suits of the Endocrine chapter: all law suits and appeals analyzed
viz <-
  plot_ly(
    dfPlot_filter,
    y = ~ value,
    color = ~ document,
    type = "box",
    colors = doc.colors,
    showlegend = FALSE,
    width = 500,
    height = 500
  ) %>%
  layout(
    title = paste0(
      "Granted values for moral damages related to \nthe same law suits of the ",
      group_cids[9, "CID_NOME_EN"],
      " chapter: \nall law suits and appeals analyzed"
    ),
    yaxis = list(font = f, title = "Amount (R$)"),
    xaxis = list(
      font = f,
      title = "",
      ticktext = list(
        paste0("Report \n(N = ", R_N[[1]], ")"),
        paste0("Lower Court \n(N = ", R_L[[1]], ")"),
        paste0("Appellate Court \n(N = ", R_A[[1]], ")")
      ),
      tickvals = list("R", "1a", "2a"),
      tickmode = "array",
      categoryarray = c("R", "1a", "2a"),
      categoryorder = "array"
    ),
    
    margin = m
  )

viz


```

Row
-------------------------------------

### 

```{r}

# filter Mental chapter
dfPlot_filter <-
  dfPlot %>% filter(CID_GRUPO == as.character(group_cids[10, "CID_GRUPO"]))

# count documents for display on the axis
R_N <- dfPlot_filter %>% filter(document == "R") %>% summarise(n())
R_L <- dfPlot_filter %>% filter(document == "1a") %>% summarise(n())
R_A <- dfPlot_filter %>% filter(document == "2a") %>% summarise(n())

# generate plot:: Granted values for moral damages related to the same law suits of the Mental chapter: all law suits and appeals analyzed
viz <-
  plot_ly(
    dfPlot_filter,
    y = ~ value,
    color = ~ document,
    type = "box",
    colors = doc.colors,
    showlegend = FALSE,
    width = 500,
    height = 500
  ) %>%
  layout(
    title = paste0(
      "Granted values for moral damages related to \nthe same law suits of the ",
      group_cids[10, "CID_NOME_EN"],
      " chapter: \nall law suits and appeals analyzed"
    ),
    yaxis = list(font = f, title = "Amount (R$)"),
    xaxis = list(
      font = f,
      title = "",
      ticktext = list(
        paste0("Report \n(N = ", R_N[[1]], ")"),
        paste0("Lower Court \n(N = ", R_L[[1]], ")"),
        paste0("Appellate Court \n(N = ", R_A[[1]], ")")
      ),
      tickvals = list("R", "1a", "2a"),
      tickmode = "array",
      categoryarray = c("R", "1a", "2a"),
      categoryorder = "array"
    ),
    
    margin = m
  )

viz


```

### 


```{r}

# filter Circulatory chapter
dfPlot_filter <-
  dfPlot %>% filter(CID_GRUPO == as.character(group_cids[11, "CID_GRUPO"]))

# count documents for display on the axis
R_N <- dfPlot_filter %>% filter(document == "R") %>% summarise(n())
R_L <- dfPlot_filter %>% filter(document == "1a") %>% summarise(n())
R_A <- dfPlot_filter %>% filter(document == "2a") %>% summarise(n())

# generate plot:: Granted values for moral damages related to the same law suits of the Circulatory chapter: all law suits and appeals analyzed
viz <-
  plot_ly(
    dfPlot_filter,
    y = ~ value,
    color = ~ document,
    type = "box",
    colors = doc.colors,
    showlegend = FALSE,
    width = 500,
    height = 500
  ) %>%
  layout(
    title = paste0(
      "Granted values for moral damages related to \nthe same law suits of the ",
      group_cids[11, "CID_NOME_EN"],
      " chapter: \nall law suits and appeals analyzed"
    ),
    yaxis = list(font = f, title = "Amount (R$)"),
    xaxis = list(
      font = f,
      title = "",
      ticktext = list(
        paste0("Report \n(N = ", R_N[[1]], ")"),
        paste0("Lower Court \n(N = ", R_L[[1]], ")"),
        paste0("Appellate Court \n(N = ", R_A[[1]], ")")
      ),
      tickvals = list("R", "1a", "2a"),
      tickmode = "array",
      categoryarray = c("R", "1a", "2a"),
      categoryorder = "array"
    ),
    
    margin = m
  )

viz


```

### 



```{r}

# filter Musculoskeletal chapter
dfPlot_filter <-
  dfPlot %>% filter(CID_GRUPO == as.character(group_cids[12, "CID_GRUPO"]))

# count documents for display on the axis
R_N <- dfPlot_filter %>% filter(document == "R") %>% summarise(n())
R_L <- dfPlot_filter %>% filter(document == "1a") %>% summarise(n())
R_A <- dfPlot_filter %>% filter(document == "2a") %>% summarise(n())

# generate plot:: Granted values for moral damages related to the same law suits of the Musculoskeletal chapter: all law suits and appeals analyzed
viz <-
  plot_ly(
    dfPlot_filter,
    y = ~ value,
    color = ~ document,
    type = "box",
    colors = doc.colors,
    showlegend = FALSE,
    width = 500,
    height = 500
  ) %>%
  layout(
    title = paste0(
      "Granted values for moral damages related to \nthe same law suits of the ",
      group_cids[12, "CID_NOME_EN"],
      " chapter: \nall law suits and appeals analyzed"
    ),
    yaxis = list(font = f, title = "Amount (R$)"),
    xaxis = list(
      font = f,
      title = "",
      ticktext = list(
        paste0("Report \n(N = ", R_N[[1]], ")"),
        paste0("Lower Court \n(N = ", R_L[[1]], ")"),
        paste0("Appellate Court \n(N = ", R_A[[1]], ")")
      ),
      tickvals = list("R", "1a", "2a"),
      tickmode = "array",
      categoryarray = c("R", "1a", "2a"),
      categoryorder = "array"
    ),
    
    margin = m
  )

viz


```


Row
-------------------------------------

### 

```{r}

# filter Genitourinary chapter
dfPlot_filter <-
  dfPlot %>% filter(CID_GRUPO == as.character(group_cids[13, "CID_GRUPO"]))

# count documents for display on the axis
R_N <- dfPlot_filter %>% filter(document == "R") %>% summarise(n())
R_L <- dfPlot_filter %>% filter(document == "1a") %>% summarise(n())
R_A <- dfPlot_filter %>% filter(document == "2a") %>% summarise(n())

# generate plot:: Granted values for moral damages related to the same law suits of the Genitourinary chapter: all law suits and appeals analyzed
viz <-
  plot_ly(
    dfPlot_filter,
    y = ~ value,
    color = ~ document,
    type = "box",
    colors = doc.colors,
    showlegend = FALSE,
    width = 500,
    height = 500
  ) %>%
  layout(
    title = paste0(
      "Granted values for moral damages related to \nthe same law suits of the ",
      group_cids[13, "CID_NOME_EN"],
      " chapter: \nall law suits and appeals analyzed"
    ),
    yaxis = list(font = f, title = "Amount (R$)"),
    xaxis = list(
      font = f,
      title = "",
      ticktext = list(
        paste0("Report \n(N = ", R_N[[1]], ")"),
        paste0("Lower Court \n(N = ", R_L[[1]], ")"),
        paste0("Appellate Court \n(N = ", R_A[[1]], ")")
      ),
      tickvals = list("R", "1a", "2a"),
      tickmode = "array",
      categoryarray = c("R", "1a", "2a"),
      categoryorder = "array"
    ),
    
    margin = m
  )

viz


```


Granted appeals {data-navmenu="Moral damage" data-icon="fa-check-circle"} 
=========================================================================================================

###
> Granted appeals

Row
---------------------------------------------------------------------------------------------------------

```{r}

# database for plotting Granted appeals
dfPlot <- dfRepTrialAppell_dm %>%
  filter(Filename %in% dfAppellbyCID_dm$Filename)
dfPlot <- dfPlot %>% filter(!(document == "R" & value == "0"))
```


### Report
```{r}

# display number of reports documents
R_N <- dfPlot %>% filter(document == "R") %>% summarise(n())
valueBox(value = R_N,
         icon = "fa-balance-scale",
         color = doc.colors[1])
```

### Lower Court
```{r}

# display number of lower court documents
R_L <- dfPlot %>% filter(document == "1a") %>% summarise(n())
valueBox(value = R_L,
         icon = "fa-balance-scale",
         color = doc.colors[2])

```

### Appellate Court
```{r}

# display number of appellate court documents
R_A <- dfPlot %>% filter(document == "2a") %>% summarise(n())
valueBox(value = R_A,
         icon = "fa-balance-scale",
         color = doc.colors[3])
```


Row {data-width: 1000}
---------------------------------------------------------------------------------------------------------

### 

```{r}

# generate plot:: Granted values for moral damages related to the same law suits: only granted appeals
viz <- plot_ly(
  dfPlot,
  y = ~ value,
  color = ~ document,
  type = "box",
  colors = doc.colors,
  showlegend = FALSE,
  width = 500,
  height = 500
) %>%
  layout(
    title = "Granted values for moral damages related to \nthe same law suits: only granted appeals",
    yaxis = list(font = f, title = "Amount (R$)"),
    xaxis = list(
      font = f,
      title = "",
      ticktext = list(
        paste0("Report \n(N = ", R_N[[1]], ")"),
        paste0("Lower Court \n(N = ", R_L[[1]], ")"),
        paste0("Appellate Court \n(N = ", R_A[[1]], ")")
      ),
      tickvals = list("R", "1a", "2a"),
      tickmode = "array",
      categoryarray = c("R", "1a", "2a"),
      categoryorder = "array"
    ),
    margin = m
  )

viz

```


Row
-------------------------------------

###

```{r}

# filter Unfefined chapter
dfPlot_filter <-
  dfPlot %>% filter(CID_GRUPO == as.character(group_cids[1, "CID_GRUPO"]))

# count documents for display on the axis
R_N <- dfPlot_filter %>% filter(document == "R") %>% summarise(n())
R_L <- dfPlot_filter %>% filter(document == "1a") %>% summarise(n())
R_A <- dfPlot_filter %>% filter(document == "2a") %>% summarise(n())

# generate plot:: Granted values for moral damages related to the same law suits of the Undefined chapter: only granted appeals
viz <-
  plot_ly(
    dfPlot_filter,
    y = ~ value,
    color = ~ document,
    type = "box",
    colors = doc.colors,
    showlegend = FALSE,
    width = 500,
    height = 500
  ) %>%
  layout(
    title = paste0(
      "Granted values for moral damages related to\n the same law suits of the ",
      group_cids[1, "CID_NOME_EN"],
      " chapter:\nonly granted appeals"
    ),
    yaxis = list(font = f, title = "Amount (R$)"),
    xaxis = list(
      font = f,
      title = "",
      ticktext = list(
        paste0("Report \n(N = ", R_N[[1]], ")"),
        paste0("Lower Court \n(N = ", R_L[[1]], ")"),
        paste0("Appellate Court \n(N = ", R_A[[1]], ")")
      ),
      tickvals = list("R", "1a", "2a"),
      tickmode = "array",
      categoryarray = c("R", "1a", "2a"),
      categoryorder = "array"
    ),
    margin = m
  )

viz

```


### 

```{r}

# filter Respiratory chapter
dfPlot_filter <-
  dfPlot %>% filter(CID_GRUPO == as.character(group_cids[2, "CID_GRUPO"]))

# count documents for display on the axis
R_N <- dfPlot_filter %>% filter(document == "R") %>% summarise(n())
R_L <- dfPlot_filter %>% filter(document == "1a") %>% summarise(n())
R_A <- dfPlot_filter %>% filter(document == "2a") %>% summarise(n())

# generate plot:: Granted values for moral damages related to the same law suits of the Respiratory chapter: only granted appeals
viz <-
  plot_ly(
    dfPlot_filter,
    y = ~ value,
    color = ~ document,
    type = "box",
    colors = doc.colors,
    showlegend = FALSE,
    width = 500,
    height = 500
  ) %>%
  layout(
    title = paste0(
      "Granted values for moral damages related to\n the same law suits of the ",
      group_cids[2, "CID_NOME_EN"],
      " chapter:\nonly granted appeals"
    ),
    yaxis = list(font = f, title = "Amount (R$)"),
    xaxis = list(
      font = f,
      title = "",
      ticktext = list(
        paste0("Report \n(N = ", R_N[[1]], ")"),
        paste0("Lower Court \n(N = ", R_L[[1]], ")"),
        paste0("Appellate Court \n(N = ", R_A[[1]], ")")
      ),
      tickvals = list("R", "1a", "2a"),
      tickmode = "array",
      categoryarray = c("R", "1a", "2a"),
      categoryorder = "array"
    ),
    margin = m
  )

viz

```

### 

```{r}

# filter Digestive chapter
dfPlot_filter <-
  dfPlot %>% filter(CID_GRUPO == as.character(group_cids[3, "CID_GRUPO"]))

# count documents for display on the axis
R_N <- dfPlot_filter %>% filter(document == "R") %>% summarise(n())
R_L <- dfPlot_filter %>% filter(document == "1a") %>% summarise(n())
R_A <- dfPlot_filter %>% filter(document == "2a") %>% summarise(n())

# generate plot:: Granted values for moral damages related to the same law suits of the Digestive chapter: only granted appeals
viz <-
  plot_ly(
    dfPlot_filter,
    y = ~ value,
    color = ~ document,
    type = "box",
    colors = doc.colors,
    showlegend = FALSE,
    width = 500,
    height = 500
  ) %>%
  layout(
    title = paste0(
      "Granted values for moral damages related to\n the same law suits of the ",
      group_cids[3, "CID_NOME_EN"],
      " chapter:\nonly granted appeals"
    ),
    yaxis = list(font = f, title = "Amount (R$)"),
    xaxis = list(
      font = f,
      title = "",
      ticktext = list(
        paste0("Report \n(N = ", R_N[[1]], ")"),
        paste0("Lower Court \n(N = ", R_L[[1]], ")"),
        paste0("Appellate Court \n(N = ", R_A[[1]], ")")
      ),
      tickvals = list("R", "1a", "2a"),
      tickmode = "array",
      categoryarray = c("R", "1a", "2a"),
      categoryorder = "array"
    ),
    margin = m
  )

viz

```


Row
-------------------------------------

### 

```{r}

# filter Eye chapter
dfPlot_filter <-
  dfPlot %>% filter(CID_GRUPO == as.character(group_cids[4, "CID_GRUPO"]))

# count documents for display on the axis
R_N <- dfPlot_filter %>% filter(document == "R") %>% summarise(n())
R_L <- dfPlot_filter %>% filter(document == "1a") %>% summarise(n())
R_A <- dfPlot_filter %>% filter(document == "2a") %>% summarise(n())

# generate plot:: Granted values for moral damages related to the same law suits of the Eye chapter: only granted appeals
viz <-
  plot_ly(
    dfPlot_filter,
    y = ~ value,
    color = ~ document,
    type = "box",
    colors = doc.colors,
    showlegend = FALSE,
    width = 500,
    height = 500
  ) %>%
  layout(
    title = paste0(
      "Granted values for moral damages related to\n the same law suits of the ",
      group_cids[4, "CID_NOME_EN"],
      " chapter:\nonly granted appeals"
    ),
    yaxis = list(font = f, title = "Amount (R$)"),
    xaxis = list(
      font = f,
      title = "",
      ticktext = list(
        paste0("Report \n(N = ", R_N[[1]], ")"),
        paste0("Lower Court \n(N = ", R_L[[1]], ")"),
        paste0("Appellate Court \n(N = ", R_A[[1]], ")")
      ),
      tickvals = list("R", "1a", "2a"),
      tickmode = "array",
      categoryarray = c("R", "1a", "2a"),
      categoryorder = "array"
    ),
    margin = m
  )

viz

```


### 

```{r}

# filter Congenital chapter
dfPlot_filter <-
  dfPlot %>% filter(CID_GRUPO == as.character(group_cids[5, "CID_GRUPO"]))

# count documents for display on the axis
R_N <- dfPlot_filter %>% filter(document == "R") %>% summarise(n())
R_L <- dfPlot_filter %>% filter(document == "1a") %>% summarise(n())
R_A <- dfPlot_filter %>% filter(document == "2a") %>% summarise(n())

# generate plot:: Granted values for moral damages related to the same law suits of the Congenital chapter: only granted appeals
viz <-
  plot_ly(
    dfPlot_filter,
    y = ~ value,
    color = ~ document,
    type = "box",
    colors = doc.colors,
    showlegend = FALSE,
    width = 500,
    height = 500
  ) %>%
  layout(
    title = paste0(
      "Granted values for moral damages related to\n the same law suits of the ",
      group_cids[5, "CID_NOME_EN"],
      " chapter:\nonly granted appeals"
    ),
    yaxis = list(font = f, title = "Amount (R$)"),
    xaxis = list(
      font = f,
      title = "",
      ticktext = list(
        paste0("Report \n(N = ", R_N[[1]], ")"),
        paste0("Lower Court \n(N = ", R_L[[1]], ")"),
        paste0("Appellate Court \n(N = ", R_A[[1]], ")")
      ),
      tickvals = list("R", "1a", "2a"),
      tickmode = "array",
      categoryarray = c("R", "1a", "2a"),
      categoryorder = "array"
    ),
    margin = m
  )

viz

```

### 

```{r}

# filter Neoplasm chapter
dfPlot_filter <-
  dfPlot %>% filter(CID_GRUPO == as.character(group_cids[6, "CID_GRUPO"]))

# count documents for display on the axis
R_N <- dfPlot_filter %>% filter(document == "R") %>% summarise(n())
R_L <- dfPlot_filter %>% filter(document == "1a") %>% summarise(n())
R_A <- dfPlot_filter %>% filter(document == "2a") %>% summarise(n())

# generate plot:: Granted values for moral damages related to the same law suits of the Neoplasm chapter: only granted appeals
viz <-
  plot_ly(
    dfPlot_filter,
    y = ~ value,
    color = ~ document,
    type = "box",
    colors = doc.colors,
    showlegend = FALSE,
    width = 500,
    height = 500
  ) %>%
  layout(
    title = paste0(
      "Granted values for moral damages related to\n the same law suits of the ",
      group_cids[6, "CID_NOME_EN"],
      " chapter:\nonly granted appeals"
    ),
    yaxis = list(font = f, title = "Amount (R$)"),
    xaxis = list(
      font = f,
      title = "",
      ticktext = list(
        paste0("Report \n(N = ", R_N[[1]], ")"),
        paste0("Lower Court \n(N = ", R_L[[1]], ")"),
        paste0("Appellate Court \n(N = ", R_A[[1]], ")")
      ),
      tickvals = list("R", "1a", "2a"),
      tickmode = "array",
      categoryarray = c("R", "1a", "2a"),
      categoryorder = "array"
    ),
    margin = m
  )

viz

```

Row
-------------------------------------

###

```{r}

# filter Not informed chapter
dfPlot_filter <-
  dfPlot %>% filter(CID_GRUPO == as.character(group_cids[7, "CID_GRUPO"]))

# count documents for display on the axis
R_N <- dfPlot_filter %>% filter(document == "R") %>% summarise(n())
R_L <- dfPlot_filter %>% filter(document == "1a") %>% summarise(n())
R_A <- dfPlot_filter %>% filter(document == "2a") %>% summarise(n())

# generate plot:: Granted values for moral damages related to the same law suits of the Not informed chapter: only granted appeals
viz <-
  plot_ly(
    dfPlot_filter,
    y = ~ value,
    color = ~ document,
    type = "box",
    colors = doc.colors,
    showlegend = FALSE,
    width = 500,
    height = 500
  ) %>%
  layout(
    title = paste0(
      "Granted values for moral damages related to\n the same law suits of the ",
      group_cids[7, "CID_NOME_EN"],
      " chapter:\nonly granted appeals"
    ),
    yaxis = list(font = f, title = "Amount (R$)"),
    xaxis = list(
      font = f,
      title = "",
      ticktext = list(
        paste0("Report \n(N = ", R_N[[1]], ")"),
        paste0("Lower Court \n(N = ", R_L[[1]], ")"),
        paste0("Appellate Court \n(N = ", R_A[[1]], ")")
      ),
      tickvals = list("R", "1a", "2a"),
      tickmode = "array",
      categoryarray = c("R", "1a", "2a"),
      categoryorder = "array"
    ),
    margin = m
  )

viz

```


### 

```{r}

# filter Infectious chapter
dfPlot_filter <-
  dfPlot %>% filter(CID_GRUPO == as.character(group_cids[8, "CID_GRUPO"]))

# count documents for display on the axis
R_N <- dfPlot_filter %>% filter(document == "R") %>% summarise(n())
R_L <- dfPlot_filter %>% filter(document == "1a") %>% summarise(n())
R_A <- dfPlot_filter %>% filter(document == "2a") %>% summarise(n())

# generate plot:: Granted values for moral damages related to the same law suits of the Infectious chapter: only granted appeals
viz <-
  plot_ly(
    dfPlot_filter,
    y = ~ value,
    color = ~ document,
    type = "box",
    colors = doc.colors,
    showlegend = FALSE,
    width = 500,
    height = 500
  ) %>%
  layout(
    title = paste0(
      "Granted values for moral damages related to\n the same law suits of the ",
      group_cids[8, "CID_NOME_EN"],
      " chapter:\nonly granted appeals"
    ),
    yaxis = list(font = f, title = "Amount (R$)"),
    xaxis = list(
      font = f,
      title = "",
      ticktext = list(
        paste0("Report \n(N = ", R_N[[1]], ")"),
        paste0("Lower Court \n(N = ", R_L[[1]], ")"),
        paste0("Appellate Court \n(N = ", R_A[[1]], ")")
      ),
      tickvals = list("R", "1a", "2a"),
      tickmode = "array",
      categoryarray = c("R", "1a", "2a"),
      categoryorder = "array"
    ),
    margin = m
  )

viz

```

### 

```{r}

# filter Endocrine chapter
dfPlot_filter <-
  dfPlot %>% filter(CID_GRUPO == as.character(group_cids[9, "CID_GRUPO"]))

# count documents for display on the axis
R_N <- dfPlot_filter %>% filter(document == "R") %>% summarise(n())
R_L <- dfPlot_filter %>% filter(document == "1a") %>% summarise(n())
R_A <- dfPlot_filter %>% filter(document == "2a") %>% summarise(n())

# generate plot:: Granted values for moral damages related to the same law suits of the Endocrine chapter: only granted appeals
viz <-
  plot_ly(
    dfPlot_filter,
    y = ~ value,
    color = ~ document,
    type = "box",
    colors = doc.colors,
    showlegend = FALSE,
    width = 500,
    height = 500
  ) %>%
  layout(
    title = paste0(
      "Granted values for moral damages related to\n the same law suits of the ",
      group_cids[9, "CID_NOME_EN"],
      " chapter:\nonly granted appeals"
    ),
    yaxis = list(font = f, title = "Amount (R$)"),
    xaxis = list(
      font = f,
      title = "",
      ticktext = list(
        paste0("Report \n(N = ", R_N[[1]], ")"),
        paste0("Lower Court \n(N = ", R_L[[1]], ")"),
        paste0("Appellate Court \n(N = ", R_A[[1]], ")")
      ),
      tickvals = list("R", "1a", "2a"),
      tickmode = "array",
      categoryarray = c("R", "1a", "2a"),
      categoryorder = "array"
    ),
    margin = m
  )

viz

```

Row
-------------------------------------

### 

```{r}

#filter Mental chapter
dfPlot_filter <-
  dfPlot %>% filter(CID_GRUPO == as.character(group_cids[10, "CID_GRUPO"]))

# count documents for display on the axis
R_N <- dfPlot_filter %>% filter(document == "R") %>% summarise(n())
R_L <- dfPlot_filter %>% filter(document == "1a") %>% summarise(n())
R_A <- dfPlot_filter %>% filter(document == "2a") %>% summarise(n())

# generate plot:: Granted values for moral damages related to the same law suits of the Mental chapter: only granted appeals
viz <-
  plot_ly(
    dfPlot_filter,
    y = ~ value,
    color = ~ document,
    type = "box",
    colors = doc.colors,
    showlegend = FALSE,
    width = 500,
    height = 500
  ) %>%
  layout(
    title = paste0(
      "Granted values for moral damages related to\n the same law suits of the ",
      group_cids[10, "CID_NOME_EN"],
      " chapter:\nonly granted appeals"
    ),
    yaxis = list(font = f, title = "Amount (R$)"),
    xaxis = list(
      font = f,
      title = "",
      ticktext = list(
        paste0("Report \n(N = ", R_N[[1]], ")"),
        paste0("Lower Court \n(N = ", R_L[[1]], ")"),
        paste0("Appellate Court \n(N = ", R_A[[1]], ")")
      ),
      tickvals = list("R", "1a", "2a"),
      tickmode = "array",
      categoryarray = c("R", "1a", "2a"),
      categoryorder = "array"
    ),
    margin = m
  )

viz

```


### 

```{r}

# filter Corculatory chapter
dfPlot_filter <-
  dfPlot %>% filter(CID_GRUPO == as.character(group_cids[11, "CID_GRUPO"]))

# count documents for display on the axis
R_N <- dfPlot_filter %>% filter(document == "R") %>% summarise(n())
R_L <- dfPlot_filter %>% filter(document == "1a") %>% summarise(n())
R_A <- dfPlot_filter %>% filter(document == "2a") %>% summarise(n())

# generate plot:: Granted values for moral damages related to the same law suits of the Circulatory chapter: only granted appeals
viz <-
  plot_ly(
    dfPlot_filter,
    y = ~ value,
    color = ~ document,
    type = "box",
    colors = doc.colors,
    showlegend = FALSE,
    width = 500,
    height = 500
  ) %>%
  layout(
    title = paste0(
      "Granted values for moral damages related to\n the same law suits of the ",
      group_cids[11, "CID_NOME_EN"],
      " chapter:\nonly granted appeals"
    ),
    yaxis = list(font = f, title = "Amount (R$)"),
    xaxis = list(
      font = f,
      title = "",
      ticktext = list(
        paste0("Report \n(N = ", R_N[[1]], ")"),
        paste0("Lower Court \n(N = ", R_L[[1]], ")"),
        paste0("Appellate Court \n(N = ", R_A[[1]], ")")
      ),
      tickvals = list("R", "1a", "2a"),
      tickmode = "array",
      categoryarray = c("R", "1a", "2a"),
      categoryorder = "array"
    ),
    margin = m
  )

viz

```

### 

```{r}

# filter Musculoskeletal chapter
dfPlot_filter <-
  dfPlot %>% filter(CID_GRUPO == as.character(group_cids[12, "CID_GRUPO"]))

# count documents for display on the axis
R_N <- dfPlot_filter %>% filter(document == "R") %>% summarise(n())
R_L <- dfPlot_filter %>% filter(document == "1a") %>% summarise(n())
R_A <- dfPlot_filter %>% filter(document == "2a") %>% summarise(n())

# generate plot:: Granted values for moral damages related to the same law suits of the  Muskuloskeletal chapter: only granted appeals
viz <-
  plot_ly(
    dfPlot_filter,
    y = ~ value,
    color = ~ document,
    type = "box",
    colors = doc.colors,
    showlegend = FALSE,
    width = 500,
    height = 500
  ) %>%
  layout(
    title = paste0(
      "Granted values for moral damages related to\n the same law suits of the ",
      group_cids[12, "CID_NOME_EN"],
      " chapter:\nonly granted appeals"
    ),
    yaxis = list(font = f, title = "Amount (R$)"),
    xaxis = list(
      font = f,
      title = "",
      ticktext = list(
        paste0("Report \n(N = ", R_N[[1]], ")"),
        paste0("Lower Court \n(N = ", R_L[[1]], ")"),
        paste0("Appellate Court \n(N = ", R_A[[1]], ")")
      ),
      tickvals = list("R", "1a", "2a"),
      tickmode = "array",
      categoryarray = c("R", "1a", "2a"),
      categoryorder = "array"
    ),
    margin = m
  )

viz

```

Row
-------------------------------------

### 

```{r}

# filter Genitourinary chapter
dfPlot_filter <-
  dfPlot %>% filter(CID_GRUPO == as.character(group_cids[13, "CID_GRUPO"]))

# count documents for display on the axis
R_N <- dfPlot_filter %>% filter(document == "R") %>% summarise(n())
R_L <- dfPlot_filter %>% filter(document == "1a") %>% summarise(n())
R_A <- dfPlot_filter %>% filter(document == "2a") %>% summarise(n())

# generate plot:: Granted values for moral damages related to the same law suits of the Genitourinary chapter: only granted appeals
viz <-
  plot_ly(
    dfPlot_filter,
    y = ~ value,
    color = ~ document,
    type = "box",
    colors = doc.colors,
    showlegend = FALSE,
    width = 500,
    height = 500
  ) %>%
  layout(
    title = paste0(
      "Granted values for moral damages related to\n the same law suits of the ",
      group_cids[13, "CID_NOME_EN"],
      " chapter:\nonly granted appeals"
    ),
    yaxis = list(font = f, title = "Amount (R$)"),
    xaxis = list(
      font = f,
      title = "",
      ticktext = list(
        paste0("Report \n(N = ", R_N[[1]], ")"),
        paste0("Lower Court \n(N = ", R_L[[1]], ")"),
        paste0("Appellate Court \n(N = ", R_A[[1]], ")")
      ),
      tickvals = list("R", "1a", "2a"),
      tickmode = "array",
      categoryarray = c("R", "1a", "2a"),
      categoryorder = "array"
    ),
    margin = m
  )

viz

```


Denied appeals {data-navmenu="Moral damage" data-icon="fa-times-circle"}
=========================================================================================================
###
> Denied appeals

Row
---------------------------------------------------------------------------------------------------------

```{r}

# database for plotting Denied appeals
dfPlot <- dfRepTrialAppell_dm %>%
  filter(!(Filename %in% dfAppellbyCID_dm$Filename))
dfPlot <- dfPlot %>% filter(!(document == "R" & value == "0"))
```

### Report
```{r}

# display number of reports documents
R_N <- dfPlot %>% filter(document == "R") %>% summarise(n())
valueBox(value = R_N,
         icon = "fa-balance-scale",
         color = doc.colors[1])
```

### Lower Court
```{r}

# display number of lower court documents
R_L <- dfPlot %>% filter(document == "1a") %>% summarise(n())
valueBox(value = R_L,
         icon = "fa-balance-scale",
         color = doc.colors[2])

```

### Appellate Court
```{r}

# display number of appllate court documents
R_A <- dfPlot %>% filter(document == "2a") %>% summarise(n())
valueBox(value = R_A,
         icon = "fa-balance-scale",
         color = doc.colors[3])
```

Row {data-width: 1000}
-------------------------------------

### 

```{r}

# generate plot:: Granted values for moral damages related to the same law suits: only denied appeals
viz <-
  plot_ly(
    dfPlot,
    y = ~ value,
    color = ~ document,
    type = "box",
    colors = doc.colors,
    showlegend = FALSE,
    width = 500,
    height = 500
  ) %>%
  layout(
    title = "Granted values for moral damages related to \nthe same law suits: only denied appeals",
    yaxis = list(font = f, title = "Amount (R$)"),
    xaxis = list(
      font = f,
      title = "",
      ticktext = list(
        paste0("Report \n(N = ", R_N[[1]], ")"),
        paste0("Lower Court \n(N = ", R_L[[1]], ")")
      ),
      tickvals = list("R", "1a", "2a"),
      tickmode = "array",
      categoryarray = c("R", "1a", "2a"),
      categoryorder = "array"
    ),
    margin = m
  )

viz

```


Row
-------------------------------------

### 

```{r}

# filter Undefined chapter
dfPlot_filter <-
  dfPlot %>% filter(CID_GRUPO == as.character(group_cids[1, "CID_GRUPO"]))

# count documents for display on the axis
R_N <- dfPlot_filter %>% filter(document == "R") %>% summarise(n())
R_L <- dfPlot_filter %>% filter(document == "1a") %>% summarise(n())

# generate plot:: Granted values for moral damages related to the same law suits of the Undefined chapter: only denied appeals
viz <-
  plot_ly(
    dfPlot_filter,
    y = ~ value,
    color = ~ document,
    type = "box",
    colors = doc.colors,
    showlegend = FALSE,
    width = 500,
    height = 500
  ) %>%
  layout(
    title = paste0(
      "Granted values for moral damages related to \nthe same law suits of the ",
      as.character(group_cids[1, "CID_NOME_EN"]),
      " chapter:\nonly denied appeals"
    ),
    yaxis = list(font = f, title = "Amount (R$)"),
    xaxis = list(
      font = f,
      title = "",
      ticktext = list(
        paste0("Report \n(N = ", R_N[[1]], ")"),
        paste0("Lower Court \n(N = ", R_L[[1]], ")")
      ),
      tickvals = list("R", "1a", "2a"),
      tickmode = "array",
      categoryarray = c("R", "1a", "2a"),
      categoryorder = "array"
    ),
    margin = m
  )

viz

```

### 

```{r}

# filter Respiratory chapter
dfPlot_filter <-
  dfPlot %>% filter(CID_GRUPO == as.character(group_cids[2, "CID_GRUPO"]))

# count documents for display on the axis
R_N <- dfPlot_filter %>% filter(document == "R") %>% summarise(n())
R_L <- dfPlot_filter %>% filter(document == "1a") %>% summarise(n())

# Granted values for moral damages related to the same law suits of the Respiratory chapter: only denied appeals
viz <-
  plot_ly(
    dfPlot_filter,
    y = ~ value,
    color = ~ document,
    type = "box",
    colors = doc.colors,
    showlegend = FALSE,
    width = 500,
    height = 500
  ) %>%
  layout(
    title = paste0(
      "Granted values for moral damages related to \nthe same law suits of the ",
      group_cids[2, "CID_NOME_EN"],
      " chapter:\nonly denied appeals"
    ),
    yaxis = list(font = f, title = "Amount (R$)"),
    xaxis = list(
      font = f,
      title = "",
      ticktext = list(
        paste0("Report \n(N = ", R_N[[1]], ")"),
        paste0("Lower Court \n(N = ", R_L[[1]], ")")
      ),
      tickvals = list("R", "1a", "2a"),
      tickmode = "array",
      categoryarray = c("R", "1a", "2a"),
      categoryorder = "array"
    ),
    margin = m
  )

viz

```

### 

```{r}

# filter Digestive chapter
dfPlot_filter <-
  dfPlot %>% filter(CID_GRUPO == as.character(group_cids[3, "CID_GRUPO"]))

# count documents for display on the axis
R_N <- dfPlot_filter %>% filter(document == "R") %>% summarise(n())
R_L <- dfPlot_filter %>% filter(document == "1a") %>% summarise(n())

# Granted values for moral damages related to the same law suits of the Digestive chapter: only denied appeals
viz <-
  plot_ly(
    dfPlot_filter,
    y = ~ value,
    color = ~ document,
    type = "box",
    colors = doc.colors,
    showlegend = FALSE,
    width = 500,
    height = 500
  ) %>%
  layout(
    title = paste0(
      "Granted values for moral damages related to \nthe same law suits of the ",
      group_cids[3, "CID_NOME_EN"] ,
      " chapter:\nonly denied appeals"
    ),
    yaxis = list(
      font = f,
      title = "Amount (R$)",
      dtick = 10000
    ),
    xaxis = list(
      font = f,
      title = "",
      ticktext = list(
        paste0("Report \n(N = ", R_N[[1]], ")"),
        paste0("Lower Court \n(N = ", R_L[[1]], ")")
      ),
      tickvals = list("R", "1a", "2a"),
      tickmode = "array",
      categoryarray = c("R", "1a", "2a"),
      categoryorder = "array"
    ),
    margin = m
  )

viz

```

Row
-------------------------------------

### 

```{r}

# filter Eye chapter
dfPlot_filter <-
  dfPlot %>% filter(CID_GRUPO == as.character(group_cids[4, "CID_GRUPO"]))

# count documents for display on the axis
R_N <- dfPlot_filter %>% filter(document == "R") %>% summarise(n())
R_L <- dfPlot_filter %>% filter(document == "1a") %>% summarise(n())

# Granted values for moral damages related to the same law suits of the Eye chapter: only denied appeals
viz <-
  plot_ly(
    dfPlot_filter,
    y = ~ value,
    color = ~ document,
    type = "box",
    colors = doc.colors,
    showlegend = FALSE,
    width = 500,
    height = 500
  ) %>%
  layout(
    title = paste0(
      "Granted values for moral damages related to \nthe same law suits of the ",
      as.character(group_cids[4, "CID_NOME_EN"]),
      " chapter:\nonly denied appeals"
    ),
    yaxis = list(font = f, title = "Amount (R$)"),
    xaxis = list(
      font = f,
      title = "",
      ticktext = list(
        paste0("Report \n(N = ", R_N[[1]], ")"),
        paste0("Lower Court \n(N = ", R_L[[1]], ")")
      ),
      tickvals = list("R", "1a", "2a"),
      tickmode = "array",
      categoryarray = c("R", "1a", "2a"),
      categoryorder = "array"
    ),
    margin = m
  )

viz

```

### 

```{r}

# filter Congenital chapter
dfPlot_filter <-
  dfPlot %>% filter(CID_GRUPO == as.character(group_cids[5, "CID_GRUPO"]))

# count documents for display on the axis
R_N <- dfPlot_filter %>% filter(document == "R") %>% summarise(n())
R_L <- dfPlot_filter %>% filter(document == "1a") %>% summarise(n())

# Granted values for moral damages related to the same law suits of the Congenital chapter: only denied appeals
viz <-
  plot_ly(
    dfPlot_filter,
    y = ~ value,
    color = ~ document,
    type = "box",
    colors = doc.colors,
    showlegend = FALSE,
    width = 500,
    height = 500
  ) %>%
  layout(
    title = paste0(
      "Granted values for moral damages related to \nthe same law suits of the ",
      group_cids[5, "CID_NOME_EN"],
      " chapter:\nonly denied appeals"
    ),
    yaxis = list(font = f, title = "Amount (R$)"),
    xaxis = list(
      font = f,
      title = "",
      ticktext = list(
        paste0("Report \n(N = ", R_N[[1]], ")"),
        paste0("Lower Court \n(N = ", R_L[[1]], ")")
      ),
      tickvals = list("R", "1a", "2a"),
      tickmode = "array",
      categoryarray = c("R", "1a", "2a"),
      categoryorder = "array"
    ),
    margin = m
  )

viz

```

### 

```{r}

# filter Neoplasm chapter
dfPlot_filter <-
  dfPlot %>% filter(CID_GRUPO == as.character(group_cids[6, "CID_GRUPO"]))

# count documents for display on the axis
R_N <- dfPlot_filter %>% filter(document == "R") %>% summarise(n())
R_L <- dfPlot_filter %>% filter(document == "1a") %>% summarise(n())

# Granted values for moral damages related to the same law suits of the Neoplasm chapter: only denied appeals
viz <-
  plot_ly(
    dfPlot_filter,
    y = ~ value,
    color = ~ document,
    type = "box",
    colors = doc.colors,
    showlegend = FALSE,
    width = 500,
    height = 500
  ) %>%
  layout(
    title = paste0(
      "Granted values for moral damages related to \nthe same law suits of the ",
      group_cids[6, "CID_NOME_EN"] ,
      " chapter:\nonly denied appeals"
    ),
    yaxis = list(
      font = f,
      title = "Amount (R$)",
      dtick = 10000
    ),
    xaxis = list(
      font = f,
      title = "",
      ticktext = list(
        paste0("Report \n(N = ", R_N[[1]], ")"),
        paste0("Lower Court \n(N = ", R_L[[1]], ")")
      ),
      tickvals = list("R", "1a", "2a"),
      tickmode = "array",
      categoryarray = c("R", "1a", "2a"),
      categoryorder = "array"
    ),
    margin = m
  )

viz

```

Row
-------------------------------------

### 

```{r}

# filter Not informed chapter
dfPlot_filter <-
  dfPlot %>% filter(CID_GRUPO == as.character(group_cids[7, "CID_GRUPO"]))

# count documents for display on the axis
R_N <- dfPlot_filter %>% filter(document == "R") %>% summarise(n())
R_L <- dfPlot_filter %>% filter(document == "1a") %>% summarise(n())

# generate plot:: Granted values for moral damages related to the same law suits of the Not informed chapter: only denied appeals
viz <-
  plot_ly(
    dfPlot_filter,
    y = ~ value,
    color = ~ document,
    type = "box",
    colors = doc.colors,
    showlegend = FALSE,
    width = 500,
    height = 500
  ) %>%
  layout(
    title = paste0(
      "Granted values for moral damages related to \nthe same law suits of the ",
      as.character(group_cids[7, "CID_NOME_EN"]),
      " chapter:\nonly denied appeals"
    ),
    yaxis = list(font = f, title = "Amount (R$)"),
    xaxis = list(
      font = f,
      title = "",
      ticktext = list(
        paste0("Report \n(N = ", R_N[[1]], ")"),
        paste0("Lower Court \n(N = ", R_L[[1]], ")")
      ),
      tickvals = list("R", "1a", "2a"),
      tickmode = "array",
      categoryarray = c("R", "1a", "2a"),
      categoryorder = "array"
    ),
    margin = m
  )

viz

```

### 

```{r}

# filter Infectious chapter
dfPlot_filter <-
  dfPlot %>% filter(CID_GRUPO == as.character(group_cids[8, "CID_GRUPO"]))

# count documents for display on the axis
R_N <- dfPlot_filter %>% filter(document == "R") %>% summarise(n())
R_L <- dfPlot_filter %>% filter(document == "1a") %>% summarise(n())

# Granted values for moral damages related to the same law suits of the Infectious chapter: only denied appeals
viz <-
  plot_ly(
    dfPlot_filter,
    y = ~ value,
    color = ~ document,
    type = "box",
    colors = doc.colors,
    showlegend = FALSE,
    width = 500,
    height = 500
  ) %>%
  layout(
    title = paste0(
      "Granted values for moral damages related to \nthe same law suits of the ",
      group_cids[8, "CID_NOME_EN"],
      " chapter:\nonly denied appeals"
    ),
    yaxis = list(font = f, title = "Amount (R$)"),
    xaxis = list(
      font = f,
      title = "",
      ticktext = list(
        paste0("Report \n(N = ", R_N[[1]], ")"),
        paste0("Lower Court \n(N = ", R_L[[1]], ")")
      ),
      tickvals = list("R", "1a", "2a"),
      tickmode = "array",
      categoryarray = c("R", "1a", "2a"),
      categoryorder = "array"
    ),
    margin = m
  )

viz

```

### 

```{r}

# filter Endocrine chapter
dfPlot_filter <-
  dfPlot %>% filter(CID_GRUPO == as.character(group_cids[9, "CID_GRUPO"]))

# count documents for display on the axis
R_N <- dfPlot_filter %>% filter(document == "R") %>% summarise(n())
R_L <- dfPlot_filter %>% filter(document == "1a") %>% summarise(n())

# Granted values for moral damages related to the same law suits of the Endocrine chapter: only denied appeals
viz <-
  plot_ly(
    dfPlot_filter,
    y = ~ value,
    color = ~ document,
    type = "box",
    colors = doc.colors,
    showlegend = FALSE,
    width = 500,
    height = 500
  ) %>%
  layout(
    title = paste0(
      "Granted values for moral damages related to \nthe same law suits of the ",
      group_cids[9, "CID_NOME_EN"] ,
      " chapter:\nonly denied appeals"
    ),
    yaxis = list(
      font = f,
      title = "Amount (R$)",
      dtick = 10000
    ),
    xaxis = list(
      font = f,
      title = "",
      ticktext = list(
        paste0("Report \n(N = ", R_N[[1]], ")"),
        paste0("Lower Court \n(N = ", R_L[[1]], ")")
      ),
      tickvals = list("R", "1a", "2a"),
      tickmode = "array",
      categoryarray = c("R", "1a", "2a"),
      categoryorder = "array"
    ),
    margin = m
  )

viz

```

Row
-------------------------------------

### 

```{r}

# filter Mental chapter
dfPlot_filter <-
  dfPlot %>% filter(CID_GRUPO == as.character(group_cids[10, "CID_GRUPO"]))

# count documents for display on the axis
R_N <- dfPlot_filter %>% filter(document == "R") %>% summarise(n())
R_L <- dfPlot_filter %>% filter(document == "1a") %>% summarise(n())

# generate plot:: Granted values for moral damages related to the same law suits of the Mental chapter: only denied appeals
viz <-
  plot_ly(
    dfPlot_filter,
    y = ~ value,
    color = ~ document,
    type = "box",
    colors = doc.colors,
    showlegend = FALSE,
    width = 500,
    height = 500
  ) %>%
  layout(
    title = paste0(
      "Granted values for moral damages related to \nthe same law suits of the ",
      as.character(group_cids[10, "CID_NOME_EN"]),
      " chapter:\nonly denied appeals"
    ),
    yaxis = list(font = f, title = "Amount (R$)"),
    xaxis = list(
      font = f,
      title = "",
      ticktext = list(
        paste0("Report \n(N = ", R_N[[1]], ")"),
        paste0("Lower Court \n(N = ", R_L[[1]], ")")
      ),
      tickvals = list("R", "1a", "2a"),
      tickmode = "array",
      categoryarray = c("R", "1a", "2a"),
      categoryorder = "array"
    ),
    margin = m
  )

viz

```

### 

```{r}

# filter Circulatory chapter
dfPlot_filter <-
  dfPlot %>% filter(CID_GRUPO == as.character(group_cids[11, "CID_GRUPO"]))

# count documents for display on the axis
R_N <- dfPlot_filter %>% filter(document == "R") %>% summarise(n())
R_L <- dfPlot_filter %>% filter(document == "1a") %>% summarise(n())

# Granted values for moral damages related to the same law suits of the Circulatory chapter: only denied appeals
viz <-
  plot_ly(
    dfPlot_filter,
    y = ~ value,
    color = ~ document,
    type = "box",
    colors = doc.colors,
    showlegend = FALSE,
    width = 500,
    height = 500
  ) %>%
  layout(
    title = paste0(
      "Granted values for moral damages related to \nthe same law suits of the ",
      group_cids[11, "CID_NOME_EN"],
      " chapter:\nonly denied appeals"
    ),
    yaxis = list(font = f, title = "Amount (R$)"),
    xaxis = list(
      font = f,
      title = "",
      ticktext = list(
        paste0("Report \n(N = ", R_N[[1]], ")"),
        paste0("Lower Court \n(N = ", R_L[[1]], ")")
      ),
      tickvals = list("R", "1a", "2a"),
      tickmode = "array",
      categoryarray = c("R", "1a", "2a"),
      categoryorder = "array"
    ),
    margin = m
  )

viz

```

### 

```{r}

# filter Musculoskeletal chapter
dfPlot_filter <-
  dfPlot %>% filter(CID_GRUPO == as.character(group_cids[12, "CID_GRUPO"]))

# count documents for display on the axis
R_N <- dfPlot_filter %>% filter(document == "R") %>% summarise(n())
R_L <- dfPlot_filter %>% filter(document == "1a") %>% summarise(n())

# Granted values for moral damages related to the same law suits of the Musculoskeletal chapter: only denied appeals
viz <-
  plot_ly(
    dfPlot_filter,
    y = ~ value,
    color = ~ document,
    type = "box",
    colors = doc.colors,
    showlegend = FALSE,
    width = 500,
    height = 500
  ) %>%
  layout(
    title = paste0(
      "Granted values for moral damages related to \nthe same law suits of the ",
      group_cids[12, "CID_NOME_EN"] ,
      " chapter:\nonly denied appeals"
    ),
    yaxis = list(
      font = f,
      title = "Amount (R$)",
      dtick = 10000
    ),
    xaxis = list(
      font = f,
      title = "",
      ticktext = list(
        paste0("Report \n(N = ", R_N[[1]], ")"),
        paste0("Lower Court \n(N = ", R_L[[1]], ")")
      ),
      tickvals = list("R", "1a", "2a"),
      tickmode = "array",
      categoryarray = c("R", "1a", "2a"),
      categoryorder = "array"
    ),
    margin = m
  )

viz

```

Row
-------------------------------------

### 

```{r}

# filter Genitourinary chapter
dfPlot_filter <-
  dfPlot %>% filter(CID_GRUPO == as.character(group_cids[13, "CID_GRUPO"]))

# count documents for display on the axis
R_N <- dfPlot_filter %>% filter(document == "R") %>% summarise(n())
R_L <- dfPlot_filter %>% filter(document == "1a") %>% summarise(n())

# generate plot:: Granted values for moral damages related to the same law suits of the Genitourinary chapter: only denied appeals
viz <-
  plot_ly(
    dfPlot_filter,
    y = ~ value,
    color = ~ document,
    type = "box",
    colors = doc.colors,
    showlegend = FALSE,
    width = 500,
    height = 500
  ) %>%
  layout(
    title = paste0(
      "Granted values for moral damages related to \nthe same law suits of the ",
      as.character(group_cids[13, "CID_NOME_EN"]),
      " chapter:\nonly denied appeals"
    ),
    yaxis = list(font = f, title = "Amount (R$)"),
    xaxis = list(
      font = f,
      title = "",
      ticktext = list(
        paste0("Report \n(N = ", R_N[[1]], ")"),
        paste0("Lower Court \n(N = ", R_L[[1]], ")")
      ),
      tickvals = list("R", "1a", "2a"),
      tickmode = "array",
      categoryarray = c("R", "1a", "2a"),
      categoryorder = "array"
    ),
    margin = m
  )

viz

```


Other claims 
=========================================================================================================
<!-- {data-icon="fa-briefcase-medical"} -->
###
> Other claims

Row {data-width: 1000}
-------------------------------------
### 
```{r}

# cids translations
cids_names <-
  c(
    "Undefined",
    "Infectious",
    "Neoplasm",
    "Blood",
    "Endocrine",
    "Mental",
    "Nervous",
    "Eye",
    "Ear",
    "Circulatory",
    "Respiratory",
    "Digestive",
    "Skin",
    "Musculoskeletal",
    "Genitourinary",
    "Childbirth and post-childbirth",
    "Perinatal",
    "Congenital",
    "Exams",
    "Poisoning",
    "Death",
    "Health services",
    "Not informed"
  )

names(cids_names) <-
  c(
    "Indefinido",
    "Infecciosas",
    "Tumores",
    "Sangue",
    "Endcrinas",
    "Mentais",
    "Sistema nervoso",
    "Oftalmolgicas",
    "Auditivas",
    "Ap. circulatrio",
    "Ap. respiratrio",
    "Ap. Digestivo",
    "Dermatolgicas",
    "Osteomuscular",
    "Ap. Urinrio",
    "Parto e ps-parto",
    "Gravidez",
    "Congnitas",
    "Exames",
    "Envenenamento",
    "Morte",
    "Servio sade",
    "No informado"
  )

dfRepTrialAppell_reemb[, "CID_NOME_EN"] <-
  cids_names[dfRepTrialAppell_reemb$CID_NOME]

# only Lower court decisions
temp <- dfRepTrialAppell_reemb %>%
  filter((!(
    Filename %in% dfAppellbyCID_reemb$Filename
  )))

# only cases with  material damage provided
documents_id <- temp %>%
  filter(document == "1a") %>% filter(REEMBOLSO == "1") %>% select(Filename)

# only Lower court and Appellate court decisions
temp <- dfRepTrialAppell_reemb
temp[temp$document == "1a", "document"] <- "primeira"
temp[temp$document == "2a", "document"] <- "segunda"

# calculate decision: Lower court decision minus Report requirement
temp <- temp %>%
  filter(Filename %in% documents_id$Filename) %>%
  select(Filename, document, RVALOR, CID_NOME, CID_NOME_EN) %>%
  group_by(Filename, CID_NOME) %>%
  spread(document, RVALOR) %>%
  mutate(diff_Trial = primeira - R) %>% as.data.frame()

# translate Trial decision:: equal, higher, lower :: than report requirement
temp$diff_Trial_quali <- "equal"
temp[temp$diff_Trial > 0, "diff_Trial_quali"] <- "higher"
temp[temp$diff_Trial < 0, "diff_Trial_quali"] <- "lower"

temp$CID_NOME_EN <- as.factor(temp$CID_NOME_EN)
temp$diff_Trial_quali <- as.factor(temp$diff_Trial_quali)

temp2 <- temp %>% group_by(CID_NOME_EN, diff_Trial_quali) %>%
  summarise(n = length(diff_Trial))

yform <- list(categoryorder = "array",
              categoryarray = temp2$n)

# do not display Not Informed & Undefined chapter
temp3 <-
  temp2 %>% filter(CID_NOME_EN != "Not informed" &
                     CID_NOME_EN != "Undefined") %>% group_by(CID_NOME_EN) %>% summarise(sum = sum(n))

n_order <- temp3[order(-temp3$sum), ]

dfPlot <-
  temp2 %>% filter(CID_NOME_EN != "Not informed" &
                     CID_NOME_EN != "Undefined")

dfPlot$CID_NOME_EN <-
  factor(dfPlot$CID_NOME_EN, levels = n_order$CID_NOME_EN)
dfPlot$diff_Trial_quali <-
  factor(dfPlot$diff_Trial_quali, levels = c("lower", "equal", "higher"))

# generate plot:: Material damages granted by chapter:\nonly denied appeals
viz <-
  plot_ly(
    dfPlot,
    y = ~ CID_NOME_EN ,
    x = ~ n,
    color =  ~ diff_Trial_quali,
    colors = levels.colors,
    type = "bar",
    showlegend = TRUE,
    width = 700,
    height = 500
  ) %>%
  layout(
    yaxis = list(font = f, title = '', yform),
    xaxis = list(font = f, title = ''),
    barmode = 'group',
    title = 'Material damages granted by chapter:\nonly denied appeals',
    autosize = FALSE,
    margin = m
  )

viz

```

Row
-------------------------------------
###
```{r}

documents_req <-
  dfRepTrialAppell_reemb %>% filter(REEMBOLSO == 1 &
                                      document == "2a") %>% select("Filename")

# only Lower court decisions
temp <- dfRepTrialAppell_reemb %>%
  filter((!(
    Filename %in% dfAppellbyCID_reemb$Filename
  )))
documents_req2 <-
  dfRepTrialAppell_reemb %>% filter(Filename %in% temp$Filename &
                                      REEMBOLSO == 1) %>% select("Filename")

documents_all <- rbind(documents_req, documents_req2)

# cid translation
cids_names <-
  c(
    "Undefined",
    "Infectious",
    "Neoplasm",
    "Blood",
    "Endocrine",
    "Mental",
    "Nervous",
    "Eye",
    "Ear",
    "Circulatory",
    "Respiratory",
    "Digestive",
    "Skin",
    "Musculoskeletal",
    "Genitourinary",
    "Childbirth and post-childbirth",
    "Perinatal",
    "Congenital",
    "Exams",
    "Poisoning",
    "Death",
    "Health services",
    "Not informed"
  )

names(cids_names) <-
  c(
    "Indefinido",
    "Infecciosas",
    "Tumores",
    "Sangue",
    "Endcrinas",
    "Mentais",
    "Sistema nervoso",
    "Oftalmolgicas",
    "Auditivas",
    "Ap. circulatrio",
    "Ap. respiratrio",
    "Ap. Digestivo",
    "Dermatolgicas",
    "Osteomuscular",
    "Ap. Urinrio",
    "Parto e ps-parto",
    "Gravidez",
    "Congnitas",
    "Exames",
    "Envenenamento",
    "Morte",
    "Servio sade",
    "No informado"
  )

dfRepTrialAppell_reemb[, "CID_NOME_EN"] <-
  cids_names[dfRepTrialAppell_reemb$CID_NOME]


dfReemb <- dfRepTrialAppell_reemb %>%
  group_by(CID_NOME, document, CID_NOME_EN) %>%
  filter(
    REEMBOLSO == "1" &
      Filename %in% documents_all$Filename &
      CID_NOME_EN != "Undefined" & CID_NOME_EN != "Not informed"
  ) %>%
  tally()

temp <- dfReemb %>% spread(document, n)
temp[is.na(temp$`1a`), "1a"] <- 0
temp[is.na(temp$`2a`), "2a"] <- 0

colnames(temp) <-
  c("CID_NOME", "CID_NOME_EN", "primeira", "segunda", "R")

dfPlot <-
  temp %>% group_by(CID_NOME, CID_NOME_EN) %>% mutate(Provided = primeira + segunda,
                                                      Not_provided = R - segunda - primeira)

dfPlot <-
  dfPlot %>% select(-c(R, primeira, segunda)) %>% gather(key = type, value = value,-c(CID_NOME, CID_NOME_EN))

dfPlot[dfPlot$type == "Not_provided", "type"] <- "Not provided"

temp <- dfPlot %>%
  group_by(CID_NOME_EN) %>% summarise(sum = sum(value))

n_order <- temp[order(-temp$sum), ]

dfPlot$CID_NOME_EN <-
  factor(dfPlot$CID_NOME_EN, levels = n_order$CID_NOME_EN)


dfPlot$type <-
  factor(dfPlot$type, levels = c("Provided", "Not provided"))

viz <-
  plot_ly(
    dfPlot,
    y = ~ CID_NOME_EN ,
    x = ~ value,
    color =  ~ type,
    colors = flag.colors,
    type = "bar",
    showlegend = TRUE,
    width = 700,
    height = 500
  ) %>%
  layout(
    barmode = 'stack',
    title = 'Relation between material damage claims \nand decisions of such claims by chapter',
    xaxis = list(
      font = f,
      title = '',
      dtick = 10
    ),
    yaxis = list(font = f, title = ''),
    margin = m
  )

viz

```


###
```{r}

# filter procedure claims
documents_req <-
  dfRepTrial_req %>% filter(type == "PROCEDIMENTO" &
                              document == "R" & value == "1") %>% select("Filename")

cids_names <-
  c(
    "Undefined",
    "Infectious",
    "Neoplasm",
    "Blood",
    "Endocrine",
    "Mental",
    "Nervous",
    "Eye",
    "Ear",
    "Circulatory",
    "Respiratory",
    "Digestive",
    "Skin",
    "Musculoskeletal",
    "Genitourinary",
    "Childbirth and post-childbirth",
    "Perinatal",
    "Congenital",
    "Exams",
    "Poisoning",
    "Death",
    "Health services",
    "Not informed"
  )

names(cids_names) <-
  c(
    "Indefinido",
    "Infecciosas",
    "Tumores",
    "Sangue",
    "Endcrinas",
    "Mentais",
    "Sistema nervoso",
    "Oftalmolgicas",
    "Auditivas",
    "Ap. circulatrio",
    "Ap. respiratrio",
    "Ap. Digestivo",
    "Dermatolgicas",
    "Osteomuscular",
    "Ap. Urinrio",
    "Parto e ps-parto",
    "Gravidez",
    "Congnitas",
    "Exames",
    "Envenenamento",
    "Morte",
    "Servio sade",
    "No informado"
  )

dfRepTrial_req[, "CID_NOME_EN"] <-
  cids_names[dfRepTrial_req$CID_NOME]


# filter procedure claims
temp <- dfRepTrial_req %>%
  group_by(CID_NOME, document, type, value, CID_NOME_EN) %>%
  filter(
    type == "PROCEDIMENTO" &
      Filename %in% documents_req$Filename &
      CID_NOME_EN != "Undefined"
  ) %>%
  tally()

temp <- temp %>% filter(document != "R")

temp2 <- temp %>%
  group_by(CID_NOME_EN) %>% summarise(sum = sum(n))

n_order <- temp2[order(-temp2$sum), ]

# do not display Undefined & Not informed
dfPlot <-
  temp %>% filter(CID_NOME_EN != "Undefined" &
                    CID_NOME_EN != "Not informed")

dfPlot$CID_NOME_EN <-
  factor(dfPlot$CID_NOME_EN, levels = n_order$CID_NOME_EN)

values_name <- c("Provided", "Not provided")
names(values_name) <- c("1", "0")

dfPlot[, "names_EN"] <- values_name[dfPlot$value]
dfPlot$names_EN <-
  factor(dfPlot$names_EN, levels = c("Provided", "Not provided"))


# generate plot:: Relation between procedure claims and lower Court decisions of such claims by chapter
viz <-
  plot_ly(
    dfPlot,
    y = ~ CID_NOME_EN ,
    x = ~ n,
    color =  ~ names_EN,
    colors = flag.colors,
    type = "bar",
    showlegend = TRUE,
    width = 700,
    height = 500
  ) %>%
  layout(
    barmode = 'stack',
    title = 'Relation between procedure claims and \nlower Court decisions of such claims by chapter',
    xaxis = list(
      font = f,
      title = '',
      dtick = 10
    ),
    yaxis = list(font = f, title = ''),
    margin = m
  )

viz

```

Row
-------------------------------------
###
```{r}

# filter medicine / exams claims
documents_req <-
  dfRepTrial_req %>% filter(type == "MEDICAMENTO_EME" &
                              document == "R" & value == "1") %>% select("Filename")

# filter medicine / exams claims
temp <- dfRepTrial_req %>%
  group_by(CID_NOME, document, type, value, CID_NOME_EN) %>%
  filter(
    type == "MEDICAMENTO_EME" &
      Filename %in% documents_req$Filename &
      CID_NOME_EN != "Not informed" & CID_NOME_EN != "Undefined"
  ) %>%
  tally()

temp <- temp %>% filter(document != "R")

temp2 <-
  temp %>% filter(CID_NOME_EN != "Not informed" &
                    CID_NOME_EN != "Undefined") %>%
  group_by(CID_NOME_EN) %>% summarise(sum = sum(n))

n_order <- temp2[order(-temp2$sum), ]

# do not display Undefined & Not informed
dfPlot <-
  temp %>% filter(CID_NOME_EN != "Not informed" &
                    CID_NOME_EN != "Undefined")

dfPlot$CID_NOME_EN <-
  factor(dfPlot$CID_NOME_EN, levels = n_order$CID_NOME_EN)

values_name <- c("Provided", "Not provided")
names(values_name) <- c("1", "0")

dfPlot[, "names_EN"] <- values_name[dfPlot$value]
dfPlot$names_EN <-
  factor(dfPlot$names_EN, levels = c("Provided", "Not provided"))

# generate plot:: Relation between medicine/exam claims and lower Court decisions of such claims by chapter
viz <-
  plot_ly(
    dfPlot,
    y = ~ CID_NOME_EN ,
    x = ~ n,
    color =  ~ names_EN,
    colors = flag.colors,
    type = "bar",
    showlegend = TRUE,
    width = 700,
    height = 500
  ) %>%
  layout(
    barmode = 'stack',
    title = 'Relation between medicine/exam claims and \nlower Court decisions of such claims by chapter',
    xaxis = list(
      font = f,
      title = '',
      dtick = 10
    ),
    yaxis = list(font = f, title = ''),
    margin = m
  )

viz

```

###
```{r}

# filter treatment claims
documents_req <-
  dfRepTrial_req %>% filter(type == "TRATAMENTO" &
                              document == "R" & value == "1") %>% select("Filename")

# filter treatment claims
temp <- dfRepTrial_req %>%
  group_by(CID_NOME, document, type, value, CID_NOME_EN) %>%
  filter(
    type == "TRATAMENTO" &
      Filename %in% documents_req$Filename &
      CID_NOME_EN != "Not informed" & CID_NOME_EN != "Undefined"
  ) %>%
  tally()

temp <- temp %>% filter(document != "R")

temp2 <-
  temp %>% filter(CID_NOME_EN != "Not informed" &
                    CID_NOME_EN != "Undefined") %>%
  group_by(CID_NOME_EN) %>% summarise(sum = sum(n))

n_order <- temp2[order(-temp2$sum), ]

# do not display Not informed & Undefined
dfPlot <-
  temp %>% filter(CID_NOME_EN != "Not informed" &
                    CID_NOME_EN != "Undefined")

dfPlot$CID_NOME_EN <-
  factor(dfPlot$CID_NOME_EN, levels = n_order$CID_NOME_EN)

values_name <- c("Provided", "Not provided")
names(values_name) <- c("1", "0")

dfPlot[, "names_EN"] <- values_name[dfPlot$value]
dfPlot$names_EN <-
  factor(dfPlot$names_EN, levels = c("Provided", "Not provided"))

# generate plot:: Relation between treatment claims and lower Court decisions of such claims by chapter
viz <-
  plot_ly(
    dfPlot,
    y = ~ CID_NOME_EN ,
    x = ~ n,
    color =  ~ names_EN,
    colors = flag.colors,
    type = "bar",
    showlegend = TRUE,
    width = 700,
    height = 500
  ) %>%
  layout(
    barmode = 'stack',
    title = 'Relation between treatment claims and \nlower Court decisions of such claims by chapter',
    xaxis = list(
      font = f,
      title = '',
      dtick = 10
    ),
    yaxis = list(font = f, title = ''),
    margin = m
  )

viz

```


